base: 'https://www.fahrschule-lietz.de/'
baseVariants:
  -
    base: 'https://lietz.ddev.site/'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=23'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: Fahrschule-Lietz
rootPageId: 1
routeEnhancers:
  News:
    type: Extbase
    limitToPages:
      - 3
      - 16
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/{page}'
        _controller: 'News::list'
        _arguments:
          page: currentPage
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
    defaultController: 'News::list'
    defaults:
      page: '0'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      news_title:
        type: NewsTitle
    requirements:
      page: \d+
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\nSitemap: www.fahrschule-lietz.de/sitemap.xml"
websiteTitle: Fahrschule-Lietz
